# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
version: "2"
issues:
  max-same-issues: 0

linters:
  disable-all: true
  settings:
    revive:
      rules:
        - name: unused-parameter
          disabled: true
  enable:
    - durationcheck
    - errcheck
    - forcetypeassert
    - godot
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused
    - govet
    - gosec
    - revive
    - bodyclose
  exclusions:
    paths:
      - (^|/)vendor(/|$)
      - (^|/)pkg/mod(/|$)
      - _test\.go$
      # If you want to exclude the whole pkg tree instead:
      # - (^|/)pkg(/|$)

formatters:
  enable:
    - gofmt

run:
  timeout: 5m

output:
  format: colored-line-number
